[package]
name = "Î»"
version = "0.1.0"
authors = ["pixel", "chrissx Media"]
description = "CLI for clac"
edition = "2021"

[dependencies]
clac = { path = ".." }
clap = { version = "3", features = ["derive"] }
permissions = "0.3"
rustyline = "10"
shellexpand = "2"
